package sx3Configuration.mergertool;

public enum HexConversionErrors {
  BASE_IMAGE_FILE_MISSING,
  BIT_FILE_MISSING,
  HEX_CONVERSION_FAILED,
  HEX_FILE_MISSING,
  IMAGE_CONVERSION_FAILED,
  MERGE_SUCCESS
}
