package sx3Configuration.mergertool;

public class SX3PropertiesConstants {

	public static final String NO_FILE_PATHS_ADDED_FOR_VIDEO_SOURCE_CONFIG = "No File paths are added in VIDEO_SOURCE_CONFIG.";
	public static final String VIDEO_SOURCE_CONFIG_FILE_PATH_NOT_ADDED_IN_JSON = "Video Source Config file not found.";
	public static final String NO_PART_OF_DATA = "This part of the data will be not available in merge file.";
	public static final String FIRMWARE_FOLDER = "firmware";

	public static final String SX3_DATA_DEVICE_NAME = "SX3 Data";
	public static final String SX3_HDMI_ITE_IMG_FILE_NAME = "SX3_HDMI_ITE";
	public static final String SX3_HDMI_GENERIC_IMG_FILE_NAME = "SX3_HDMI_Generic";
	public static final String SX3_IS_IMG_FILE_NAME = "SX3_IS";
	public static final String SX3_DATA_IMG_FILE_NAME = "SX3_DATA";
	public static final String SX3_UVC_DEFAULT_IMG_FILE_NAME = "SX3_UVC_DEFAULT";

	public static final String HEX_FILE_EXTENSION = ".hex";
	public static final String UNDER_SCORE = "_";
	public static final String DOT = ".";
	public static final String IMAGE_FILE_EXTENSION = ".img";
	public static final String CSV_FILE_EXTENSION = ".csv";

	public static final String SIGNATURE = "CY";
	public static final String HEX_PREFIX = "0x";
	public static final String BINAARY_PREFIX = "0b";
	public static final String NO_HEX_VALUE = "00";
	public static final String RESERVED_HEX_VALUE = "FF";
	public static final String CONFIG_TABLE_OFFSET_DEFAULT_VALUE = "0xFFFF";
	public static final String RESERVED_KEY = "RESERVED";

	public static final String CSV_FILE_GENERATION_FLAG = "csv.file.generation.flag";
	public static final String SX3_HELP_CONTENT_FILE_PATH_KEY = "sx3.help.content.file.path";
	public static final String SX3_START_PAGE_FILE_NAME_KEY = "sx3.start.content.file.path";

	public static final String HEX_VALUE_MAPPING_PROPERTIES = "/hexValueMapping.properties";

	public static final String CONFIG_TABLE_GENERAL = "CONFIG_TABLE_GENERAL";
	public static final String CONFIG_TABLE_OFFSET_TABLE = "CONFIG_TABLE_OFFSET_TABLE";
	public static final String DEVICE_SETTINGS = "DEVICE_SETTINGS";
	public static final String DEVICE_SETTINGS_USB_SETTINGS = "DEVICE_SETTINGS.USB_SETTINGS";
	public static final String DEVICE_SETTINGS_DEBUG_LEVEL = "DEVICE_SETTINGS.DEBUG_LEVEL";
	public static final String DEVICE_SETTINGS_GPIOS_SETTINGS = "DEVICE_SETTINGS.GPIOS_SETTINGS";
	public static final String DEVICE_SETTINGS_AUXILLIARY_INTERFACE = "DEVICE_SETTINGS.AUXILLIARY_INTERFACE";
	public static final String FIFO_MASTER_CONFIG = "FIFO_MASTER_CONFIG";
	public static final String VIDEO_SOURCE_CONFIG = "VIDEO_SOURCE_CONFIG";
	public static final String VIDEO_TYPE_HDMI_SOURCE_CONFIGURATION = "VIDEO_SOURCE_CONFIG.HDMI_SOURCE_CONFIGURATION";
	public static final String SLAVE_FIFO_SETTINGS = "SLAVE_FIFO_SETTINGS";
	public static final String UAC_SETTINGS = "UAC_SETTINGS";
	public static final String UAC_SETTINGS_ENDPOINT_SETTINGS = "UAC_SETTINGS.ENDPOINT_SETTINGS";
	public static final String UAC_SETTINGS_UAC_SETTING = "UAC_SETTINGS.UAC_SETTING";
	public static final String SAMPLING_FREQUENCY_1_SENSOR_CONFIG = "SAMPLING_FREQUENCY_1_SENSOR_CONFIG";
	public static final String SAMPLING_FREQUENCY_2_SENSOR_CONFIG = "SAMPLING_FREQUENCY_2_SENSOR_CONFIG";
	public static final String SAMPLING_FREQUENCY_3_SENSOR_CONFIG = "SAMPLING_FREQUENCY_3_SENSOR_CONFIG";
	public static final String SAMPLING_FREQUENCY_4_SENSOR_CONFIG = "SAMPLING_FREQUENCY_4_SENSOR_CONFIG";
	public static final String UVC_SETTINGS = "UVC_SETTINGS";
	public static final String UVC_SETTINGS_ENDPOINT_SETTINGS = "UVC_SETTINGS.ENDPOINT_SETTINGS";
	public static final String UVC_SETTINGS_FORMAT_RESOLUTION = "UVC_SETTINGS.FORMAT_RESOLUTION";
	public static final String SENSOR_CONFIG = "RESOLUTION_REGISTER_SETTING";
	public static final String UVC_SETTINGS_FORMAT_RESOLUTIONS = "UVC_SETTINGS.FORMAT_RESOLUTION.FORMAT_RESOLUTIONS";
	public static final String UVC_SETTINGS_COLOR_MATCHING = "UVC_SETTINGS.COLOR_MATCHING";
	public static final String UVC_SETTINGS_CAMERA_CONTROL = "UVC_SETTINGS.CAMERA_CONTROL";
	public static final String UVC_SETTINGS_CAMERA_CONTROLS = "UVC_SETTINGS.CAMERA_CONTROL.CAMERA_CONTROLS";
	public static final String UVC_SETTINGS_PROCESSING_UNIT_CONTROL = "UVC_SETTINGS.PROCESSING_UNIT_CONTROL";
	public static final String UVC_SETTINGS_PROCESSING_UNIT_CONTROLS = "UVC_SETTINGS.PROCESSING_UNIT_CONTROL.PROCESSING_UNIT_CONTROLS";
	public static final String UVC_SETTINGS_EXTENSION_UNIT_CONTROL = "UVC_SETTINGS.EXTENSION_UNIT_CONTROL";

	public static final String[] RESERVED = { "RESERVED" };
	public static final String[] DEVICE_SETTINGS_USB_SETTINGS_LENGTH_FIELDS = { "LEN_MANUFACTURER_STRING",
			"LEN_PRODUCT_STRING", "LEN_SERIALNUMBER" };
	/**
	 * CONFIG_TABLE_GENERAL Parameters
	 **/
	public static final String[] CONFIG_TABLE_GENERAL_FIELDS = { "SIGNATURE", "CONFIG_TABLE_CHECKSUM",
			"CONFIG_TABLE_LENGTH", "VERSION_MAJOR", "VERSION_MINOR", "VERSION_PATCH", "CONFIGURATION_TYPE",
			"RESERVED" };
	public static final int[] CONFIG_TABLE_GENERAL_BYTE_SIZES = { 2, 4, 4, 1, 1, 1, 1, 30 };

	/**
	 * CONFIG_TABLE_OFFSET_TABLE Parameters
	 **/
	public static final String[] CONFIG_TABLE_OFFSET_TABLE_FIELDS = { "SX3_DEVICE_SETTINGS_TABLE_OFFSET",
			"FIFO_MASTER_CONFIG_OFFSET", "VIDEO_SOURCE_1_CONFIG_OFFSET", "VIDEO_SOURCE_2_CONFIG_OFFSET",
			"SLAVE_FIFO_1_SETTINGS_CONFIG_TABLE_OFFSET", "SLAVE_FIFO_2_SETTINGS_CONFIG_TABLE_OFFSET",
			"UAC_1_CONFIG_TABLE_OFFSET", "UAC_2_CONFIG_TABLE_OFFSET", "UVC_1_CONFIG_TABLE_OFFSET",
			"UVC_2_CONFIG_TABLE_OFFSET", "UVC_1_COLOR_MATCHING_DESCRIPTOR_OFFSET",
			"UVC_2_COLOR_MATCHING_DESCRIPTOR_OFFSET", "UVC_1_CAMERA_CONTROLS_TABLE_OFFSET",
			"UVC_2_CAMERA_CONTROLS_TABLE_OFFSET", "UVC_1_PROCESSING_UNIT_TABLE_OFFSET",
			"UVC_2_PROCESSING_UNIT_TABLE_OFFSET", "UVC_1_EXTENSION_UNIT_TABLE_OFFSET",
			"UVC_2_EXTENSION_UNIT_TABLE_OFFSET", "RESERVED" };
	public static final int[] CONFIG_TABLE_OFFSET_TABLE_BYTE_SIZES = { 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
			2, 2, 32 };

	/**
	 * USB Settings Parameters
	 **/
	public static final String[] DEVICE_SETTINGS_USB_SETTINGS_FIELDS = { "VENDOR_ID", "PRODUCT_ID",
			"LEN_MANUFACTURER_STRING", "MANUFACTURER_STRING", "LEN_PRODUCT_STRING", "PRODUCT_STRING",
			"LEN_SERIALNUMBER", "SERIALNUMBER_STRING", "REMOTE_WAKEUP_ENABLE", "POWER_CONFIGURATION",
			"CONFIG_DSCR_LENGTH_SS", "CONFIG_DSCR_LENGTH_HS", "CONFIG_DSCR_LENGTH_FS", "ENDPOINT1_TYPE",
			"ENDPOINT2_TYPE", "FIFO_BUS_WIDTH", "FIFO_CLOCK", "FIFO_INTERFACE_TYPE", "UVC_VERSION",
			"UVC_HEADER_ADDITION", "RESERVED" };
	public static final int[] DEVICE_SETTINGS_USB_SETTINGS_BYTE_SIZES = { 2, 2, 1, 32, 1, 32, 1, 32, 1, 1, 2, 2, 2, 1,
			1, 1, 1, 1, 1, 1, 30 };

	/**
	 * Debug Settings
	 **/
	public static final String[] DEVICE_SETTINGS_DEBUG_LEVEL_FIELDS = { "DEBUG_ENABLE", "DEBUG_LEVEL",
			"AUTO_GENERATE_SERIAL_NUMBER", "RESERVED" };
	public static final int[] DEVICE_SETTINGS_DEBUG_LEVEL_BYTE_SIZES = { 1, 1, 1, 1 };

	/**
	 * GPIOS Settings
	 **/
	public static final String[] DEVICE_SETTINGS_GPIOS_SETTINGS_FIELDS = { "GPIO_0_SETTING", "GPIO_1_SETTING",
			"GPIO_2_SETTING", "GPIO_3_SETTING", "GPIO_4_SETTING", "GPIO_5_SETTING", "GPIO_6_SETTING", "RESERVED" };
	public static final int[] DEVICE_SETTINGS_GPIOS_SETTINGS_BYTE_SIZES = { 1, 1, 1, 1, 1, 1, 1, 16 };

	/**
	 * Auxilliary Interface Settings
	 **/
	public static final String[] DEVICE_SETTINGS_AUXILLIARY_INTERFACE_FIELDS = { "FIRMWARE_UPDATE_HID",
			"I2C_FREQUENCY" };
	public static final int[] DEVICE_SETTINGS_AUXILLIARY_INTERFACE_BYTE_SIZES = { 1, 1 };
	public static final int[] DEVICE_SETTINGS_RESERVED_BYTE_SIZES = { 30 };

	/**
	 * FIFO_MASTER_CONFIG Parameters
	 **/
	public static final String[] FIFO_MASTER_CONFIG_FIELDS = { "FIFO_MASTER_CONFIGURATION_DOWNLOAD_EN", "FPGA_FAMILY",
			"I2C_SLAVE_ADDRESS", "BIT_FILE_SIZE", "RESERVED" };
	public static final int[] FIFO_MASTER_CONFIG_BYTE_SIZES = { 1, 1, 1, 4, 29 };

	/**
	 * VIDEO_SOURCE_TYPE Parameters
	 **/
	public static final String[] VIDEO_SOURCE_CONFIG_FIELDS = { "VIDEO_SOURCE_TYPE", "VIDEO_SOURCE_SUBTYPE",
			"ENABLE_VIDEO_SOURCE_CONFIGURATION_DOWNLOAD", "I2C_SLAVE_ADDRESS", "I2C_SLAVE_DATA_SIZE",
			"I2C_SLAVE_REGISTER_SIZE", "HDMI_CONFIG_NUM_ROWS" };
	public static final int[] VIDEO_SOURCE_CONFIG_BYTE_SIZES = { 1, 1, 1, 1, 1, 1, 1 };

	public static final String[] HDMI_SOURCE_CONFIGURATION_FIELDS = { "HDMI_SOURCE_REGISTER_ADDRESS", "MASK_PATTERN",
			"COMPARE_VALUE", "HDMI_SOURCE_CONFIG_NUM_ROWS", "RESOLUTION_REGISTER_SETTING" };
	public static final int[] HDMI_SOURCE_CONFIGURATION_BYTE_SIZES = { 1, 1, 1, 1, 180 };
	public static final int[] VIDEO_SOURCE_CONFIG_RESERVED_BYTE_SIZES = { 35 };
	/**
	 * SLAVE_FIFO_SETTINGS Parameters
	 **/
	public static final String[] SLAVE_FIFO_SETTINGS_FIELDS = { "BURST_LENGTH", "BUFFER_COUNT", "BUFFER_SIZE",
			"RESERVED" };
	public static final int[] SLAVE_FIFO_SETTINGS_BYTE_SIZES = { 1, 1, 2, 8 };

	/**
	 * UAC_SETTINGS Parameters
	 **/
	public static final String[] UAC_SETTINGS_ENDPOINT_SETTINGS_FIELDS = { "BURST_LENGTH", "BUFFER_COUNT",
			"BUFFER_SIZE" };
	public static final int[] UAC_SETTINGS_ENDPOINT_SETTINGS_BYTE_SIZES = { 1, 1, 2 };

	public static final String[] UAC_SETTINGS_UAC_SETTING_FIELDS = { "TERMINAL_TYPE", "NUMBER_OF_CHANNELS",
			"CHANNEL_CONFIGURATION", "AUDIO_FORMAT", "BIT_RESOLUTION", "NUMBER_OF_SAMPLING_FREQUENCIES", "RESERVED",
			"SAMPLING_FREQUENCY_1", "SAMPLING_FREQUENCY_2", "SAMPLING_FREQUENCY_3", "SAMPLING_FREQUENCY_4",
			"FEATURE_UNIT_CONTROLS", "SAMPLING_FQ_1_NUM_SENSOR_WRITES", "SAMPLING_FQ_2_NUM_SENSOR_WRITES",
			"SAMPLING_FQ_3_NUM_SENSOR_WRITES", "SAMPLING_FQ_4_NUM_SENSOR_WRITES", "SAMPLING_FREQUENCY_1_SENSOR_CONFIG",
			"SAMPLING_FREQUENCY_2_SENSOR_CONFIG", "SAMPLING_FREQUENCY_3_SENSOR_CONFIG",
			"SAMPLING_FREQUENCY_4_SENSOR_CONFIG" };
	public static final int[] UAC_SETTINGS_UAC_SETTING_BYTE_SIZES = { 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
			30, 30, 30, 30 };
	public static final int[] UAC_SETTINGS_RESERVED_BYTE_SIZES = { 34 };

	/**
	 * UVC_SETTINGS Parameters
	 **/
	public static final String[] UVC_SETTINGS_ENDPOINT_SETTINGS_FIELDS = { "ENDPOINT_TRANSFER_TYPE", "BURST_LENGTH",
			"BUFFER_SIZE", "BUFFER_COUNT", "RESERVED" };
	public static final int[] UVC_SETTINGS_ENDPOINT_SETTINGS_BYTE_SIZES = { 1, 1, 2, 1, 3 };

	public static final String[] UVC_SETTINGS_FORMAT_RESOLUTION_FIELDS = { "TOTAL_NUMBER_OF_RESOLUTIONS",
			"TOTAL_NUMBER_OF_IMAGE_FORMATS_SS_ENABLED", "TOTAL_NUMBER_OF_IMAGE_FORMATS_HS_ENABLED",
			"TOTAL_NUMBER_OF_IMAGE_FORMATS_FS_ENABLED" };
	public static final int[] UVC_SETTINGS_FORMAT_RESOLUTION_BYTE_SIZES = { 1, 1, 1, 1 };

	public static final String[] UVC_SETTINGS_FORMAT_RESOLUTIONS_FIELDS = { "IMAGE_FORMAT", "BITS_PER_PIXEL",
			"H_RESOLUTION", "V_RESOLUTION", "STILL_CAPTURE", "SUPPORTED_IN_FS", "SUPPORTED_IN_HS", "SUPPORTED_IN_SS",
			"FRAME_RATE_IN_FS", "FRAME_RATE_IN_HS", "FRAME_RATE_IN_SS", "RESOLUTION_REGISTER_SETTING_LEN",
			"RESOLUTION_REGISTER_SETTING", "RESERVED" };
	public static final int[] UVC_SETTINGS_FORMAT_RESOLUTIONS_BYTE_SIZES = { 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 480,
			3 };

	// sub fields
	public static final String[] SENSOR_CONFIG_FIELDS = { "REGISTER_ADDRESS", "REGISTER_VALUE", "SLAVE_ADDRESS" };
	public static final int[] SENSOR_CONIG_BYTE_SIZES = { 2, 4, 2 };

	public static final String[] UVC_SETTINGS_COLOR_MATCHING_FIELDS = { "COLOR_PRIMARIES", "TRANSFER_CHARACTERISTICS",
			"MATRIX_COEFFICIENTS", "RESERVED" };
	public static final int[] UVC_SETTINGS_COLOR_MATCHING_BYTE_SIZES = { 1, 1, 1, 9 };

	public static final String[] UVC_SETTINGS_CAMERA_CONTROL_FIELDS = { "CAMERA_CONTROLS_ENABLED_BITMASK" };
	public static final int[] UVC_SETTINGS_CAMERA_CONTROL_BYTE_SIZES = { 4 };

	public static final String[] CAMERA_CONTROLS_ENABLED_BITMASK_FIELDS = { "D0: RESERVED", "D1: AUTO-EXPOSURE_MODE",
			"D2: AUTO-EXPOSURE_PRIORITY", "D3: EXPOSURE_TIME", "D4: RESERVED", "D5: FOCUS", "D6 : RESERVED", "D7: IRIS",
			"D8 : RESERVED", "D9: ZOOM", "D10: RESERVED", "D11: PANTILT", "D12: RESERVED", "D13: ROLL", "D14: RESERVED",
			"D15: RESERVED", "D16: RESERVED", "D17: RESERVED", "D18: RESERVED", "D19: RESERVED",
			"D20: WINDOW_CONTROL_TOP_(IN_PIXELS)", "D21: REGION_OF_INTEREST_TOP_(IN_PIXELS)", "D22: RESERVED",
			"D23: RESERVED", "D24: RESERVED", "D25: RESERVED", "D26: RESERVED", "D27: RESERVED", "D28: RESERVED",
			"D29: RESERVED", "D30: RESERVED", "D31: RESERVED" };

	public static final String[] UVC_SETTINGS_CAMERA_CONTROLS_FIELDS = { "AUTO-EXPOSURE_MODE", "AUTO-EXPOSURE_PRIORITY",
			"EXPOSURE_TIME", "FOCUS", "IRIS", "ZOOM", "PANTILT", "ROLL", "REGION_OF_INTEREST_TOP_(IN_PIXELS)",
			"REGION_OF_INTEREST_LEFT_(IN_PIXELS)", "REGION_OF_INTEREST_BOTTOM_(IN_PIXELS)",
			"REGION_OF_INTEREST_RIGHT_(IN_PIXELS)", "REGION_OF_INTEREST_AUTO_EXPOSURE", "REGION_OF_INTEREST_AUTO_IRIS",
			"REGION_OF_INTEREST_AUTO_WHITE_BALANCE", "REGION_OF_INTEREST_AUTO_FOCUS",
			"REGION_OF_INTEREST_AUTO_FACE_DETECT", "REGION_OF_INTEREST_AUTO_DETECT_AND_TRACK",
			"REGION_OF_INTEREST_IMAGE_STABILIZATION", "REGION_OF_INTERESTHIGHER_QUALITY",
			"WINDOW_CONTROL_TOP_(IN_PIXELS)", "WINDOW_CONTROL_LEFT_(IN_PIXELS)", "WINDOW_CONTROL_BOTTOM_(IN_PIXELS)",
			"WINDOW_CONTROL_RIGHT_(IN_PIXELS)", "WINDOW_CONTROL_NUMSTEPS_(IN_PIXELS)",
			"WINDOW_CONTROL_NUMSTEPSUNITS_(IN_PIXELS)" };

	public static final String[] UVC_SETTINGS_PROCESSING_UNIT_CONTROL_FIELDS = {
			"PROCESSING_UNIT_ENABLED_CONTROLS_BITMASK" };
	public static final int[] UVC_SETTINGS_PROCESSING_UNIT_CONTROL_BYTE_SIZES = { 4 };

	public static final String[] PROCESSING_UNIT_ENABLED_CONTROLS_BITMASK_FIELDS = { "D0: BRIGHTNESS", "D1: CONTRAST",
			"D2: HUE", "D3: SATURATION", "D4: SHARPNESS", "D5: GAMMA", "D6: WHITE_BALANCE_TEMPERATURE",
			"D7: WHITE_BALANCE_COMPONENT", "D8: BACKLIGHT_COMPENSATION", "D9: GAIN", "D10: POWER_LINE_FREQUENCY",
			"D11: HUE,_AUTO", "D12: WHITE_BALANCE_TEMPERATURE,_AUTO", "D13: WHITE_BALANCE_COMPONENT,_AUTO",
			"D14: RESERVED", "D15: RESERVED", "D16: RESERVED", "D17: RESERVED", "D18: RESERVED", "D19: RESERVED",
			"D20: RESERVED", "D21: RESERVED", "D22: RESERVED", "D23: RESERVED", "D24: RESERVED", "D25: RESERVED",
			"D26: RESERVED", "D27: RESERVED", "D28: RESERVED", "D29: RESERVED", "D30: RESERVED", "D31: RESERVED" };

	public static final String[] UVC_SETTINGS_PROCESSING_UNIT_CONTROLS_FIELDS = { "BRIGHTNESS", "CONTRAST", "HUE",
			"SATURATION", "SHARPNESS", "GAMMA", "WHITE_BALANCE_TEMPERATURE", "WHITE_BALANCE_COMPONENT",
			"BACKLIGHT_COMPENSATION", "GAIN", "POWER_LINE_FREQUENCY", "HUE,_AUTO", "WHITE_BALANCE_TEMPERATURE,_AUTO",
			"WHITE_BALANCE_COMPONENT,_AUTO" };

	public static final String[] UVC_SETTINGS_EXTENSION_UNIT_CONTROL_FIELDS = { "DEVICE_RESET_VENDOR_COMMAND_ENABLED",
			"I2C_READ_VENDOR_COMMAND_ENABLED", "I2C_WRITE_VENDOR_COMMAND_ENABLED",
			"FIRMWARE_VERSION_VENDOR_COMMAND_ENABLED" };
	public static final int[] UVC_SETTINGS_EXTENSION_UNIT_CONTROL_BYTE_SIZES = { 1, 1, 1, 1 };

	public static final String[] UVC_SETTINGS_EXTENDED_FIELDS = { "ENABLE", "MIN", "MAX", "STEP", "DEFAULT",
			"CURRENT_VALUE", "REGISTER_ADDRESS", "LENGTH", "RESERVED" };
	public static final int[] UVC_SETTINGS_EXTENDED_BYTE_SIZES = { 4, 4, 4, 4, 4, 4, 2, 1, 5 };
	public static final int[] UVC_SETTINGS_RESERVED_BYTE_SIZES = { 16 };

	public static String[] getMainFieldAppendedWithExtendedFields(String mainField) {
		String[] result = new String[UVC_SETTINGS_EXTENDED_FIELDS.length];
		int i = 0;
		for (String extendedField : SX3PropertiesConstants.UVC_SETTINGS_EXTENDED_FIELDS) {
			result[i++] = mainField + SX3PropertiesConstants.UNDER_SCORE + extendedField;
		}
		return result;
	}

	public static int[] getMainFieldByteSizesForExtendedFields(String mainField) {
		int[] mainFieldPlusExtendedFieldByteSize = new int[UVC_SETTINGS_EXTENDED_FIELDS.length];
		int j = 0;
		for (int byteSize : SX3PropertiesConstants.UVC_SETTINGS_EXTENDED_BYTE_SIZES) {
			mainFieldPlusExtendedFieldByteSize[j++] = byteSize;
		}
		return mainFieldPlusExtendedFieldByteSize;
	}

	public static final String DEVICE_SETTINGS_TOOLTIP_PROPERTIES = "/sx3ConfigurationTooltipAndError.properties";

}
