package sx3Configuration.util;

public class DEVICE_SETTINGS_HELP {
	private USB_SETTINGS_HELP USB_SETTINGS;
	private GPIOS_SETTINGS_HELP GPIOS_SETTINGS;
	private DEBUG_LEVEL_HELP DEBUG_LEVEL;
	private AUXILLIARY_INTERFACE_HELP AUXILLIARY_INTERFACE;
	public AUXILLIARY_INTERFACE_HELP getAUXILLIARY_INTERFACE() {
		return AUXILLIARY_INTERFACE;
	}
	public void setAUXILLIARY_INTERFACE(AUXILLIARY_INTERFACE_HELP aUXILLIARY_INTERFACE) {
		AUXILLIARY_INTERFACE = aUXILLIARY_INTERFACE;
	}
	public USB_SETTINGS_HELP getUSB_SETTINGS() {
		return USB_SETTINGS;
	}
	public void setUSB_SETTINGS(USB_SETTINGS_HELP uSB_SETTINGS) {
		USB_SETTINGS = uSB_SETTINGS;
	}
	public GPIOS_SETTINGS_HELP getGPIOS_SETTINGS() {
		return GPIOS_SETTINGS;
	}
	public void setGPIOS_SETTINGS(GPIOS_SETTINGS_HELP gPIOS_SETTINGS) {
		GPIOS_SETTINGS = gPIOS_SETTINGS;
	}
	public DEBUG_LEVEL_HELP getDEBUG_LEVEL() {
		return DEBUG_LEVEL;
	}
	public void setDEBUG_LEVEL(DEBUG_LEVEL_HELP dEBUG_LEVEL) {
		DEBUG_LEVEL = dEBUG_LEVEL;
	}
	
	
}
