package sx3Configuration.model;

public class ConfigTableOffSetTable {

	private String SX3_DEVICE_SETTINGS_TABLE_OFFSET;
	private String FIFO_MASTER_CONFIG_OFFSET;
	private String VIDEO_SOURCE_1_CONFIG_OFFSET;
	private String VIDEO_SOURCE_2_CONFIG_OFFSET;
	private String SLAVE_FIFO_1_SETTINGS_CONFIG_TABLE_OFFSET;
	private String SLAVE_FIFO_2_SETTINGS_CONFIG_TABLE_OFFSET;
	private String UAC_1_CONFIG_TABLE_OFFSET;
	private String UAC_2_CONFIG_TABLE_OFFSET;
	private String UVC_1_CONFIG_TABLE_OFFSET;
	private String UVC_2_CONFIG_TABLE_OFFSET;
	private String UVC_1_COLOR_MATCHING_DESCRIPTOR_OFFSET;
	private String UVC_2_COLOR_MATCHING_DESCRIPTOR_OFFSET;
	private String UVC_1_CAMERA_CONTROLS_TABLE_OFFSET;
	private String UVC_2_CAMERA_CONTROLS_TABLE_OFFSET;
	private String UVC_1_PROCESSING_UNIT_TABLE_OFFSET;
	private String UVC_2_PROCESSING_UNIT_TABLE_OFFSET;
	private String UVC_1_EXTENSION_UNIT_TABLE_OFFSET;
	private String UVC_2_EXTENSION_UNIT_TABLE_OFFSET;
	private String RESERVED;

	public String getSX3_DEVICE_SETTINGS_TABLE_OFFSET() {
		return SX3_DEVICE_SETTINGS_TABLE_OFFSET;
	}

	public void setSX3_DEVICE_SETTINGS_TABLE_OFFSET(String sX3_DEVICE_SETTINGS_TABLE_OFFSET) {
		SX3_DEVICE_SETTINGS_TABLE_OFFSET = sX3_DEVICE_SETTINGS_TABLE_OFFSET;
	}

	public String getFIFO_MASTER_CONFIG_OFFSET() {
		return FIFO_MASTER_CONFIG_OFFSET;
	}

	public void setFIFO_MASTER_CONFIG_OFFSET(String fIFO_MASTER_CONFIG_OFFSET) {
		FIFO_MASTER_CONFIG_OFFSET = fIFO_MASTER_CONFIG_OFFSET;
	}

	public String getVIDEO_SOURCE_1_CONFIG_OFFSET() {
		return VIDEO_SOURCE_1_CONFIG_OFFSET;
	}

	public void setVIDEO_SOURCE_1_CONFIG_OFFSET(String vIDEO_SOURCE_1_CONFIG_OFFSET) {
		VIDEO_SOURCE_1_CONFIG_OFFSET = vIDEO_SOURCE_1_CONFIG_OFFSET;
	}
	
	public String getVIDEO_SOURCE_2_CONFIG_OFFSET() {
		return VIDEO_SOURCE_2_CONFIG_OFFSET;
	}

	public void setVIDEO_SOURCE_2_CONFIG_OFFSET(String vIDEO_SOURCE_2_CONFIG_OFFSET) {
		VIDEO_SOURCE_2_CONFIG_OFFSET = vIDEO_SOURCE_2_CONFIG_OFFSET;
	}

	public String getSLAVE_FIFO_1_SETTINGS_CONFIG_TABLE_OFFSET() {
		return SLAVE_FIFO_1_SETTINGS_CONFIG_TABLE_OFFSET;
	}

	public void setSLAVE_FIFO_1_SETTINGS_CONFIG_TABLE_OFFSET(String sLAVE_FIFO_1_SETTINGS_CONFIG_TABLE_OFFSET) {
		SLAVE_FIFO_1_SETTINGS_CONFIG_TABLE_OFFSET = sLAVE_FIFO_1_SETTINGS_CONFIG_TABLE_OFFSET;
	}

	public String getSLAVE_FIFO_2_SETTINGS_CONFIG_TABLE_OFFSET() {
		return SLAVE_FIFO_2_SETTINGS_CONFIG_TABLE_OFFSET;
	}

	public void setSLAVE_FIFO_2_SETTINGS_CONFIG_TABLE_OFFSET(String sLAVE_FIFO_2_SETTINGS_CONFIG_TABLE_OFFSET) {
		SLAVE_FIFO_2_SETTINGS_CONFIG_TABLE_OFFSET = sLAVE_FIFO_2_SETTINGS_CONFIG_TABLE_OFFSET;
	}

	public String getUAC_1_CONFIG_TABLE_OFFSET() {
		return UAC_1_CONFIG_TABLE_OFFSET;
	}

	public void setUAC_1_CONFIG_TABLE_OFFSET(String uAC_1_CONFIG_TABLE_OFFSET) {
		UAC_1_CONFIG_TABLE_OFFSET = uAC_1_CONFIG_TABLE_OFFSET;
	}

	public String getUAC_2_CONFIG_TABLE_OFFSET() {
		return UAC_2_CONFIG_TABLE_OFFSET;
	}

	public void setUAC_2_CONFIG_TABLE_OFFSET(String uAC_2_CONFIG_TABLE_OFFSET) {
		UAC_2_CONFIG_TABLE_OFFSET = uAC_2_CONFIG_TABLE_OFFSET;
	}

	public String getUVC_1_CONFIG_TABLE_OFFSET() {
		return UVC_1_CONFIG_TABLE_OFFSET;
	}

	public void setUVC_1_CONFIG_TABLE_OFFSET(String uVC_1_CONFIG_TABLE_OFFSET) {
		UVC_1_CONFIG_TABLE_OFFSET = uVC_1_CONFIG_TABLE_OFFSET;
	}

	public String getUVC_1_COLOR_MATCHING_DESCRIPTOR_OFFSET() {
		return UVC_1_COLOR_MATCHING_DESCRIPTOR_OFFSET;
	}

	public void setUVC_1_COLOR_MATCHING_DESCRIPTOR_OFFSET(String uVC_1_COLOR_MATCHING_DESCRIPTOR_OFFSET) {
		UVC_1_COLOR_MATCHING_DESCRIPTOR_OFFSET = uVC_1_COLOR_MATCHING_DESCRIPTOR_OFFSET;
	}

	public String getUVC_1_CAMERA_CONTROLS_TABLE_OFFSET() {
		return UVC_1_CAMERA_CONTROLS_TABLE_OFFSET;
	}

	public void setUVC_1_CAMERA_CONTROLS_TABLE_OFFSET(String uVC_1_CAMERA_CONTROLS_TABLE_OFFSET) {
		UVC_1_CAMERA_CONTROLS_TABLE_OFFSET = uVC_1_CAMERA_CONTROLS_TABLE_OFFSET;
	}

	public String getUVC_1_PROCESSING_UNIT_TABLE_OFFSET() {
		return UVC_1_PROCESSING_UNIT_TABLE_OFFSET;
	}

	public void setUVC_1_PROCESSING_UNIT_TABLE_OFFSET(String uVC_1_PROCESSING_UNIT_TABLE_OFFSET) {
		UVC_1_PROCESSING_UNIT_TABLE_OFFSET = uVC_1_PROCESSING_UNIT_TABLE_OFFSET;
	}

	public String getUVC_1_EXTENSION_UNIT_TABLE_OFFSET() {
		return UVC_1_EXTENSION_UNIT_TABLE_OFFSET;
	}

	public void setUVC_1_EXTENSION_UNIT_TABLE_OFFSET(String uVC_1_EXTENSION_UNIT_TABLE_OFFSET) {
		UVC_1_EXTENSION_UNIT_TABLE_OFFSET = uVC_1_EXTENSION_UNIT_TABLE_OFFSET;
	}

	public String getUVC_2_CONFIG_TABLE_OFFSET() {
		return UVC_2_CONFIG_TABLE_OFFSET;
	}

	public void setUVC_2_CONFIG_TABLE_OFFSET(String uVC_2_CONFIG_TABLE_OFFSET) {
		UVC_2_CONFIG_TABLE_OFFSET = uVC_2_CONFIG_TABLE_OFFSET;
	}

	public String getUVC_2_COLOR_MATCHING_DESCRIPTOR_OFFSET() {
		return UVC_2_COLOR_MATCHING_DESCRIPTOR_OFFSET;
	}

	public void setUVC_2_COLOR_MATCHING_DESCRIPTOR_OFFSET(String uVC_2_COLOR_MATCHING_DESCRIPTOR_OFFSET) {
		UVC_2_COLOR_MATCHING_DESCRIPTOR_OFFSET = uVC_2_COLOR_MATCHING_DESCRIPTOR_OFFSET;
	}

	public String getUVC_2_CAMERA_CONTROLS_TABLE_OFFSET() {
		return UVC_2_CAMERA_CONTROLS_TABLE_OFFSET;
	}

	public void setUVC_2_CAMERA_CONTROLS_TABLE_OFFSET(String uVC_2_CAMERA_CONTROLS_TABLE_OFFSET) {
		UVC_2_CAMERA_CONTROLS_TABLE_OFFSET = uVC_2_CAMERA_CONTROLS_TABLE_OFFSET;
	}

	public String getUVC_2_PROCESSING_UNIT_TABLE_OFFSET() {
		return UVC_2_PROCESSING_UNIT_TABLE_OFFSET;
	}

	public void setUVC_2_PROCESSING_UNIT_TABLE_OFFSET(String uVC_2_PROCESSING_UNIT_TABLE_OFFSET) {
		UVC_2_PROCESSING_UNIT_TABLE_OFFSET = uVC_2_PROCESSING_UNIT_TABLE_OFFSET;
	}

	public String getUVC_2_EXTENSION_UNIT_TABLE_OFFSET() {
		return UVC_2_EXTENSION_UNIT_TABLE_OFFSET;
	}

	public void setUVC_2_EXTENSION_UNIT_TABLE_OFFSET(String uVC_2_EXTENSION_UNIT_TABLE_OFFSET) {
		UVC_2_EXTENSION_UNIT_TABLE_OFFSET = uVC_2_EXTENSION_UNIT_TABLE_OFFSET;
	}

	public String getRESERVED() {
		return RESERVED;
	}

	public void setRESERVED(String rESERVED) {
		RESERVED = rESERVED;
	}

}
