package sx3Configuration.model;

import java.util.List;

public class FormatAndResolution {

	private int TOTAL_NUMBER_OF_RESOLUTIONS;
	private int TOTAL_NUMBER_OF_IMAGE_FORMATS_SS_ENABLED;
	private int TOTAL_NUMBER_OF_IMAGE_FORMATS_HS_ENABLED;
	private int TOTAL_NUMBER_OF_IMAGE_FORMATS_FS_ENABLED;
	private int TOTAL_NUMBER_OF_RESOLUTIONS_SS_ENABLED;
	private int TOTAL_NUMBER_OF_RESOLUTIONS_HS_ENABLED;
	private int TOTAL_NUMBER_OF_RESOLUTIONS_FS_ENABLED;
	private int TOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_SS;
	private int TOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_HS;
	private int TOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_FS;
	private int TOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_SS;
	private int TOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_HS;
	private int TOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_FS;
	private List<FormatAndResolutions> FORMAT_RESOLUTIONS;

	public int getTOTAL_NUMBER_OF_RESOLUTIONS() {
		return TOTAL_NUMBER_OF_RESOLUTIONS;
	}

	public void setTOTAL_NUMBER_OF_RESOLUTIONS(int tOTAL_NUMBER_OF_RESOLUTIONS) {
		TOTAL_NUMBER_OF_RESOLUTIONS = tOTAL_NUMBER_OF_RESOLUTIONS;
	}

	public int getTOTAL_NUMBER_OF_IMAGE_FORMATS_FS_ENABLED() {
		return TOTAL_NUMBER_OF_IMAGE_FORMATS_FS_ENABLED;
	}

	public void setTOTAL_NUMBER_OF_IMAGE_FORMATS_FS_ENABLED(int tOTAL_NUMBER_OF_IMAGE_FORMATS_FS_ENABLED) {
		TOTAL_NUMBER_OF_IMAGE_FORMATS_FS_ENABLED = tOTAL_NUMBER_OF_IMAGE_FORMATS_FS_ENABLED;
	}

	public int getTOTAL_NUMBER_OF_IMAGE_FORMATS_HS_ENABLED() {
		return TOTAL_NUMBER_OF_IMAGE_FORMATS_HS_ENABLED;
	}

	public void setTOTAL_NUMBER_OF_IMAGE_FORMATS_HS_ENABLED(int tOTAL_NUMBER_OF_IMAGE_FORMATS_HS_ENABLED) {
		TOTAL_NUMBER_OF_IMAGE_FORMATS_HS_ENABLED = tOTAL_NUMBER_OF_IMAGE_FORMATS_HS_ENABLED;
	}

	public int getTOTAL_NUMBER_OF_IMAGE_FORMATS_SS_ENABLED() {
		return TOTAL_NUMBER_OF_IMAGE_FORMATS_SS_ENABLED;
	}

	public void setTOTAL_NUMBER_OF_IMAGE_FORMATS_SS_ENABLED(int tOTAL_NUMBER_OF_IMAGE_FORMATS_SS_ENABLED) {
		TOTAL_NUMBER_OF_IMAGE_FORMATS_SS_ENABLED = tOTAL_NUMBER_OF_IMAGE_FORMATS_SS_ENABLED;
	}

	public List<FormatAndResolutions> getFORMAT_RESOLUTIONS() {
		return FORMAT_RESOLUTIONS;
	}

	public void setFORMAT_RESOLUTIONS(List<FormatAndResolutions> fORMAT_RESOLUTIONS) {
		FORMAT_RESOLUTIONS = fORMAT_RESOLUTIONS;
	}

	public int getTOTAL_NUMBER_OF_RESOLUTIONS_SS_ENABLED() {
		return TOTAL_NUMBER_OF_RESOLUTIONS_SS_ENABLED;
	}

	public void setTOTAL_NUMBER_OF_RESOLUTIONS_SS_ENABLED(int tOTAL_NUMBER_OF_RESOLUTIONS_SS_ENABLED) {
		TOTAL_NUMBER_OF_RESOLUTIONS_SS_ENABLED = tOTAL_NUMBER_OF_RESOLUTIONS_SS_ENABLED;
	}

	public int getTOTAL_NUMBER_OF_RESOLUTIONS_HS_ENABLED() {
		return TOTAL_NUMBER_OF_RESOLUTIONS_HS_ENABLED;
	}

	public void setTOTAL_NUMBER_OF_RESOLUTIONS_HS_ENABLED(int tOTAL_NUMBER_OF_RESOLUTIONS_HS_ENABLED) {
		TOTAL_NUMBER_OF_RESOLUTIONS_HS_ENABLED = tOTAL_NUMBER_OF_RESOLUTIONS_HS_ENABLED;
	}

	public int getTOTAL_NUMBER_OF_RESOLUTIONS_FS_ENABLED() {
		return TOTAL_NUMBER_OF_RESOLUTIONS_FS_ENABLED;
	}

	public void setTOTAL_NUMBER_OF_RESOLUTIONS_FS_ENABLED(int tOTAL_NUMBER_OF_RESOLUTIONS_FS_ENABLED) {
		TOTAL_NUMBER_OF_RESOLUTIONS_FS_ENABLED = tOTAL_NUMBER_OF_RESOLUTIONS_FS_ENABLED;
	}

	public int getTOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_SS() {
		return TOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_SS;
	}

	public void setTOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_SS(
			int tOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_SS) {
		TOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_SS = tOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_SS;
	}

	public int getTOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_HS() {
		return TOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_HS;
	}

	public void setTOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_HS(
			int tOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_HS) {
		TOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_HS = tOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_HS;
	}

	public int getTOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_FS() {
		return TOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_FS;
	}

	public void setTOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_FS(
			int tOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_FS) {
		TOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_FS = tOTAL_NUMBER_OF_IMAGE_FORMATS_WITH_STILL_CAPTURE_ENABLED_FS;
	}

	public int getTOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_SS() {
		return TOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_SS;
	}

	public void setTOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_SS(
			int tOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_SS) {
		TOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_SS = tOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_SS;
	}

	public int getTOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_HS() {
		return TOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_HS;
	}

	public void setTOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_HS(
			int tOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_HS) {
		TOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_HS = tOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_HS;
	}

	public int getTOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_FS() {
		return TOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_FS;
	}

	public void setTOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_FS(
			int tOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_FS) {
		TOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_FS = tOTAL_NUMBER_OF_RESOLUTIONS_WITH_STILL_CAPTURE_ENABLED_FS;
	}


}
